name: Build Wheels

on:
  push:
    branches:
      - package-fix
    tags:
      - 'v*'
  pull_request:

jobs:
  build_wheels_windows:
    name: Build wheels on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, x86]

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: ${{ matrix.architecture }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cmake ninja

      - name: Build SLEEF
        shell: cmd
        run: |
          git clone https://github.com/shibatch/sleef.git
          cd sleef
          cmake -G Ninja -S . -B build -DSLEEF_BUILD_QUAD:BOOL=ON -DSLEEF_BUILD_SHARED_LIBS:BOOL=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build --config Release
          cmake --install build --prefix C:\sleef

      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.20.0

      - name: Build wheels
        env:
          CIBW_BUILD: 'cp310-* cp311-* cp312-*'
          CIBW_ARCHS_WINDOWS: ${{ matrix.architecture == 'x86' && 'x86' || 'AMD64' }}
          CIBW_BUILD_VERBOSITY: '1'
          DISTUTILS_USE_SDK: '1'
          MSSdk: '1'
          PATH: C:\sleef\bin;${{ env.PATH }}
          CIBW_REPAIR_WHEEL_COMMAND: >
            delvewheel repair -w {dest_dir} {wheel}
          CIBW_BEFORE_BUILD: pip install delvewheel
          CIBW_TEST_COMMAND: |
            pip install {package}[test]
            pytest {project}\tests
          CIBW_TEST_EXTRAS: 'test'
        shell: bash
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        working-directory: ./quaddtype

      - uses: actions/upload-artifact@v4
        with:
          path: ./quaddtype/wheelhouse/*.whl
          name: wheels-windows-${{ matrix.architecture }}