[build-system]
requires = [
    "meson>=1.3.2",
    "meson-python",
    "patchelf",
    "wheel",
    "numpy"
]
build-backend = "mesonpy"

[project]
name = "quaddtype"
description = "Quad (128-bit) float dtype for numpy"
version = "0.0.1"
readme = 'README.md'
authors = [{name = "Swayam Singh", email = "singhswayam008@gmail.com"}]
requires-python = ">=3.9.0"
dependencies = [
    "numpy"
]

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.cibuildwheel]
archs = ["auto64"]
skip = ["*-musllinux*", "pp*", "cp36-*", "cp37-*", "cp38-*"]
test-command = "pytest {project}/tests"
test-extras = ["test"]

[tool.cibuildwheel.linux]
before-all = """
yum install -y wget &&
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh &&
bash miniconda.sh -b -p $HOME/miniconda &&
export PATH=$HOME/miniconda/bin:$PATH &&
conda install -y -c conda-forge sleef
"""
environment = {PATH = "$HOME/miniconda/bin:$PATH", LD_LIBRARY_PATH = "$HOME/miniconda/lib:$LD_LIBRARY_PATH"}

[tool.cibuildwheel.macos]
before-all = """
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh &&
bash miniconda.sh -b -p $HOME/miniconda &&
export PATH=$HOME/miniconda/bin:$PATH &&
conda install -y -c conda-forge sleef
"""
environment = {PATH = "$HOME/miniconda/bin:$PATH", DYLD_LIBRARY_PATH = "$HOME/miniconda/lib:$DYLD_LIBRARY_PATH"}

# [tool.cibuildwheel.windows]
# before-all = """
# powershell -Command "Invoke-WebRequest -Uri https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile miniconda.exe" &&
# start /wait "" miniconda.exe /S /D=%UserProfile%\Miniconda3 &&
# set PATH=%UserProfile%\Miniconda3;%UserProfile%\Miniconda3\Scripts;%PATH% &&
# conda install -y -c conda-forge sleef
# """
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}"