name: Release and Publish to TestPyPI

on:
  push:
    branches:
      - sep-workflows
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish_to_testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/*

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: publish_to_testpypi
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*.whl
