name: Release and Publish to TestPyPI

on:
  workflow_run:
    workflows: ["Build Macos", "Build linux", "Build win"]
    types:
      - completed
  push:
    branches:
      - sep-workflows
    tags:
      - "v*"

jobs:
  release_and_publish:
    name: Release and Publish
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download macOS artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels-macos-13
          path: dist/macos-13

      - name: Download macOS artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels-macos-14
          path: dist/macos-14

      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels-linux
          path: dist/linux

      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels-windows-x64
          path: dist/windows

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist

      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*.whl
