name: Release and Publish to TestPyPI

on:
  workflow_run:
    workflows: ["Build Macos", "Build linux", "Build win"]
    types:
      - completed
  push:
    branches:
      - sep-workflows # or whatever your default branch name is
    tags:
      - "v*"

jobs:
  debug_job:
    name: Debug Job
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  release_and_publish:
    name: Release and Publish
    needs: debug_job
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download macOS artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: wheels-macos-13
          path: dist/macos-13

      - name: Download macOS artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: wheels-macos-14
          path: dist/macos-14

      - name: Download Linux artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: wheels-linux
          path: dist/linux

      - name: Download Windows artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: wheels-windows-x64
          path: dist/windows

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist

      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*.whl
